### ISSUE TITLE
Adding support for Lifecycle Customizations 

### ISSUE THREAD

**Issue by ahmedzidan** [terraform-aws-modules/terraform-aws-ec2-instance#172]
Hello, when I try to use lifecycle to change the destroy behavior 
```
  lifecycle    {
    create_before_destroy = true
  }
```
I got this error
```
on main.tf line 84, in module "ec2_instance":
An argument named "lifecycle" is not expected here.
```
Can we add support for that?

**Comment by krystan** [comment]
> Hello, when I try to use lifecycle to change the destroy behavior
> 
> ```
>   lifecycle    {
>     create_before_destroy = true
>   }
> ```
> 
> I got this error
> 
> ```
> on main.tf line 84, in module "ec2_instance":
> An argument named "lifecycle" is not expected here.
> ```
> 
> Can we add support for that?

the module block doesn't support lifecycle events, and I suspect you will not be able to get the change you desire here as it will change the behaviour of a module in use by many thousands of people. I would fork and inject your lifecycle statements inside your fork.

**Comment by avijuran** [comment]
We have a similar issue with ignoring changes on specific values, in our case AMI IDs. We don't want TF to recreate the instances when we use wildcard AMI lookups.
Is there any reason not to add this using optional param(s), and a dynamic block?

**Comment by ag3man** [comment]
I am also wanting to using lifecycle in this module while deploying a dockerswarm.

I deploy the initial docker swarm manager 1 instance and then want to ensure userdata is not modified on the original manager, so that the other managers can join it with the unique token that was created.

Can support not be added for a variable called enable_lifecycle = TRUE | FALSE ?

The ASG module has the lifecycle block included. https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/main.tf#L54-L57

Perhaps adding this at a minimum may not cause as much of an impact for now I am going to attempt to use the ASG module to see, if I can achieve what I am looking for.

**Comment by bryantbiggs** [comment]
hi all, unfortunately parameterized lifecycle blocks is not something that is supported by Terraform (https://github.com/hashicorp/terraform/issues/3116).
