### ISSUE TITLE
`Volume_tags` not being used in `aws_instance` yet the plan show its going to set it to `null`

### ISSUE THREAD

**Issue by syed-awais-ali** [terraform-aws-modules/terraform-aws-ec2-instance#216]
## Description

I am not using `volume_tags` in any of AWS instances in my TF code and only using `tags`. I am managing the block device tags outside the `aws_instance` configuration such as using `tags` in an `aws_ebs_volume resource` attached via `aws_volume_attachment`.  This is also mentioned in the docs [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance). I have gone through the fix made in https://github.com/hashicorp/terraform-provider-aws/pull/15474, and I have also seen various ways of getting around with this but none is a suitable and long term solution to this issue. 

## Versions
We are currently at `3.23.0` but we pinned this version in our provider file since the newer version broke things for us and this has been going on for quite a while now. Do we expect a quick resolution to this?

Similar problem [here](https://github.com/hashicorp/terraform-provider-aws/pull/15474#issuecomment-760979075) and [here](https://github.com/hashicorp/terraform-provider-aws/issues/17074#issuecomment-772645914)

More comments on https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/issues/164

Temporarily to evade this you can add the following in `aws_intance` config
```
  lifecycle {
    ignore_changes = [volume_tags]
  }
```

**Comment by jonaopower** [comment]
same problem here...
it happens in version 2.18 and 2.19
If I force version 2.17, everything works great...
Looks like a bug or semantic version problem , because it should not break compatibility 

Code for version 2.17 (terraform plan works fine):
module "ec2_cluster" {
  source  = "terraform-aws-modules/ec2-instance/aws"
  version = "2.17"

  name              = var.ec2_prefix
  use_num_suffix    = var.ec2_num_suffix
  num_suffix_format = var.ec2_num_suffix_format
  instance_count    = var.ec2_count

  ami                         = var.ec2_ami
  instance_type               = var.ec2_instance_type
  key_name                    = var.ec2_key
  monitoring                  = var.ec2_monitoring
  vpc_security_group_ids      = concat([module.security_group.this_security_group_id], var.ec2_sgs_ids)
  subnet_ids                  = var.subnet_ids
  associate_public_ip_address = var.ec2_public_ip_address
  root_block_device           = var.ec2_root_block_device


  # Define tags para ec2
  #tags = var.default_tags
  #tags = merge(
  #  var.default_tags,
  #  {
  #    Name = "${var.ec2_prefix}-${instance_count.index}"
  #  },
  #)

  # Define tags para volumes disks da instancias ec2
  volume_tags = var.default_tags
  #volume_tags = merge(
  #  var.default_tags,
  #  {
  #    Name = "Disco-${var.ec2_prefix}"
  #  },
  #)

}
