### ISSUE TITLE
Multi-zone EC2 instance implementation is not possible

### ISSUE THREAD

**Issue by levmichael3** [terraform-aws-modules/terraform-aws-ec2-instance#29]
I might be missing something but I'm trying to create a multizone setup using this odule but I can't wrap my head on how to do it as in [your example](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/master/examples/basic/main.tf) it only show the first element in the VPC subnet:

`  subnet_id                   = "${element(data.aws_subnet_ids.all.ids, 0)}`

Is there a way to implement a MZ setup with this module?

**Comment by Dogers** [comment]
Looks like no as the subnet_id var is only a string? It'd need to be a list along with an element() switch in the module to pick the subnet based on count.index.
This would break backwards compatibility but should be easy enough to add - any thoughts @antonbabenko ?

**Comment by levmichael3** [comment]
@Dogers @antonbabenko Thank you first of all for the real fast response.
Secondly - my motivation was to create a cluster with dynamic number of nodes which is MZed.
Each node should have been created in a different zone dynamically so the code footprint was too long, calling the same module per zone. I gad to use Scaling group instead of this EC2 module.

**Comment by Dogers** [comment]
@antonbabenko at the moment this module can only create X instances in subnet A per call of the module. The request here is to say create X instances over subnets A, B, C.

**Comment by antonbabenko** [comment]
Yes, I understand that but I don't like this way because it hides the logic of creation of instances internally.

As a maintainer, I constantly have to think about what will happen when a user wants to create instances with different arguments (eg, security groups) depending on which subnet it is running.

Also, as a good practice and in most of the cases, you should be able to replace this module with [terraform-aws-autoscaling module](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/) when you need to deploy across several subnets.

**Comment by Dogers** [comment]
Can understand the first point and fair enough if that's the way you want it to go. Happy to keep a custom copy in this case :)

But for the second, SGs don't depend on subnets, as they're contained in the VPC rather than the subnet..?

We've got a need for this currently as we have some things that unfortunately can't be just brought up by an ASG.

**Comment by antonbabenko** [comment]
Right, example with security group was far-fetched :)
